### ISSUE TITLE
Algunos departamentos no funcionan

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/visualizaciones-electores-por-circuito-en-cordoba#3]
Al abrir Rio Cuarto, Marcos Juarez (y posiblemente otros) no andan

No se ve el detalle de los circuitos

**Comment by avdata99** [comment]
Cruz del Eje, Rio Segundo tampoco

**Comment by florenperetti** [comment]
Estás seguro de que no andan? Porque en el repo original funciona de la misma forma si no me equivoco.

**Comment by avdata99** [comment]
En el repo original funciona igual, es una falla del desarrollador original.

Como el tipo lo hace de onda no le puedo pedir a el que arregle su bug.

**Comment by florenperetti** [comment]
jjaja lo se, pero todavía no tuve tiempo de ver bien los datos para saber como _deberían_ mostrarse, simplemente lo comparé y pensé que quizás hasta ahí llegaba la visualización.
